env:
  browser: true
  es2021: true
  node: true
extends:
  - vue-global-api
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  vue/multi-word-component-names: 0
  vue/require-default-prop: 0
