extends:
  - stylelint-config-standard
  - stylelint-config-prettier
  - stylelint-config-recommended-vue
rules:
  selector-class-pattern: null
  no-descending-specificity: null
  rule-empty-line-before: null
  color-function-notation: null
  comment-empty-line-before: null
